import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * `/favicon.ico` has to exist, and has to be an ICO that says the truth.
 *
 * It was a 404 in production for the life of the app: this project ships an
 * SVG favicon and an apple-touch icon, and nothing else. Browsers are happy
 * with that; the crawlers that build site icons are not — they start at
 * `/favicon.ico` and do not read SVG, which is why a password manager's icon
 * CDN had nothing for this domain. Generated by `build-icon.py` from the same
 * mark as every other icon, so it cannot drift from them.
 *
 * Checked by DECODING it rather than by its size on disk: a file that is
 * present and not an icon serves a broken image, and both answer "exists".
 * Each directory entry is held against the dimensions the embedded PNG states
 * for itself — an entry can claim 32x32 over a 16x16 image and the file still
 * opens, in the browser, at the wrong size.
 */
describe("the favicon", () => {
  const ICO = join(import.meta.dirname, "../../public/favicon.ico");

  it("is an ICO whose entries agree with the images inside them", () => {
    const d = readFileSync(ICO);

    expect(d.readUInt16LE(0), "byte 0-1 of an ICO is reserved and must be 0").toBe(0);
    expect(d.readUInt16LE(2), "type 1 is an icon; 2 would be a cursor").toBe(1);

    const count = d.readUInt16LE(4);
    // Exact, not a floor: the population is the list in build-icon.py's ICO
    // constant, closed by construction. A floor would let a regeneration that
    // dropped a size through.
    expect(count, "expected the four sizes build-icon.py packs").toBe(4);

    const sizes: number[] = [];
    for (let i = 0; i < count; i += 1) {
      const entry = 6 + 16 * i;
      // 0 in this byte means 256 — it is one byte wide, which is the whole
      // reason the format needs the convention.
      const declared = d.readUInt8(entry) || 256;
      const offset = d.readUInt32LE(entry + 12);
      const length = d.readUInt32LE(entry + 8);

      expect(offset + length, `entry ${i} points past the end of the file`).toBeLessThanOrEqual(d.length);

      const blob = d.subarray(offset, offset + length);
      expect(
        blob.subarray(0, 4),
        `entry ${i} is not PNG data — this packer only writes PNG`,
      ).toEqual(Buffer.from([0x89, 0x50, 0x4e, 0x47]));

      // The IHDR width/height, which is what a renderer actually draws.
      expect(
        [blob.readUInt32BE(16), blob.readUInt32BE(20)],
        `entry ${i} declares ${declared}px and the image inside is not that`,
      ).toEqual([declared, declared]);

      sizes.push(declared);
    }

    expect(sizes, "the sizes a crawler and a tab bar each need").toEqual([16, 32, 48, 128]);
  });
});
