import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { basename, join } from "node:path";

/**
 * Every Swift file in the iOS app is in the tracked Xcode project, and every
 * Swift file the project names is on disk.
 *
 * project.pbxproj is generated by xcodegen and tracked, and the routine after
 * building is to revert it because xcodegen rewrites 35 object UUIDs per run
 * and that diff means nothing. It means something when a file entered or left
 * a target, and the revert cannot tell. Twice in three days:
 *
 * - a file renamed, the project still naming the old one — a clean checkout
 *   did not compile (b8f77ef);
 * - a test file added, the project not naming it — a clean checkout would
 *   build GastosTests WITHOUT it and pass green, the new tests never run
 *   (624776b). That direction is silent, which is why this exists.
 *
 * The file set is `git ls-files -co --exclude-standard`, as this repo decides
 * for "the source files": it sees the file just written and not yet staged —
 * exactly when this mistake happens — and skips anything ignored.
 */

const ROOT = join(import.meta.dirname, "../../../..");
const PBXPROJ = readFileSync(
  join(ROOT, "apps/ios/Gastos.xcodeproj/project.pbxproj"),
  "utf8",
);

const onDisk = execFileSync(
  "git",
  ["ls-files", "--cached", "--others", "--exclude-standard", "--", "apps/ios/*.swift"],
  { cwd: ROOT, encoding: "utf8" },
)
  .split("\n")
  .filter((p) => p.endsWith(".swift"))
  // `ls-files` still lists a tracked file deleted in the working tree.
  .filter((p) => {
    try {
      readFileSync(join(ROOT, p));
      return true;
    } catch {
      return false;
    }
  })
  .map((p) => basename(p));

/** Every `Name.swift` the project refers to, from its file references. */
const named = [...PBXPROJ.matchAll(/path = "?([^";/]+\.swift)"?;/g)].map((m) => m[1]);

describe("the tracked Xcode project and the Swift files on disk", () => {
  it("has files on both sides to compare", () => {
    // Anti-empty: a moved project or a changed pattern must not turn both
    // checks below into comparisons of nothing.
    expect(onDisk.length).toBeGreaterThan(50);
    expect(named.length).toBeGreaterThan(50);
  });

  it("names every Swift file that is on disk", () => {
    const missing = onDisk.filter((f) => !named.includes(f));
    expect(
      missing,
      `on disk but not in project.pbxproj — run xcodegen and commit it:\n  ${missing.join("\n  ")}`,
    ).toEqual([]);
  });

  it("has every Swift file it names on disk", () => {
    const gone = [...new Set(named)].filter((f) => !onDisk.includes(f));
    expect(
      gone,
      `in project.pbxproj but not on disk — run xcodegen and commit it:\n  ${gone.join("\n  ")}`,
    ).toEqual([]);
  });
});
